"""
AI Assistant
============
ChatGPT-style panel that answers questions about the live dashboard
state. Every answer is generated by the Query Agent, which reads the
Coordinator's merged output of the Forecast / Attribution / Enforcement
/ Advisory / Decision agents (plus a live Intervention Simulator run for
"best intervention" questions) — so every claim traces back to a named
agent + field, shown as citation chips under the answer.
"""
import streamlit as st

from agents.coordinator import Coordinator
from agents.query_agent import QueryAgent
from app.components.metric_card import section_title
from app.data_loader import build_feature_row

SUGGESTED_QUESTIONS = [
    "Why did AQI increase?",
    "What's the best intervention right now?",
    "Which area is most polluted?",
    "What's the health risk today?",
    "What's the forecast for tomorrow?",
    "Explain the source attribution.",
]


@st.cache_resource(show_spinner=False)
def _get_coordinator():
    return Coordinator()


@st.cache_resource(show_spinner=False)
def _get_query_agent():
    return QueryAgent()


def _citation_chips(citations):
    if not citations:
        return ""
    chips = "".join(
        f"<span class='badge' style='background:rgba(59,130,246,0.12); color:var(--primary); "
        f"border:1px solid rgba(59,130,246,0.3); margin-right:6px; margin-top:6px;' "
        f"title=\"{c['detail']}\">📎 {c['agent']} · {c['field']}</span>"
        for c in citations
    )
    return f"<div style='margin-top:8px;'>{chips}</div>"


def render(ctx):
    city = ctx["city"]
    clean_df = ctx["clean"]
    models = ctx["models"]
    feature_cols = ctx["feature_cols"]
    attribution_df = ctx["attribution"]
    enforcement_df = ctx["enforcement"]

    section_title("AI Assistant", "💬")
    st.markdown(
        "<div class='card-caption' style='margin-top:-8px;'>Ask about AQI trends, source attribution, "
        "the most polluted areas, health risk, forecasts, or the best intervention — every answer is grounded "
        "in this session's live agent outputs, with citations you can inspect.</div>",
        unsafe_allow_html=True,
    )

    if city.lower() not in {"delhi", "mumbai"}:
        st.info(f"The AI Assistant needs the Forecast Agent, which is only trained for Delhi and Mumbai in "
                f"this prototype. Switch the city selector to Delhi or Mumbai to chat.")
        return

    city_data = clean_df[clean_df["City"] == city].sort_values("Date")
    latest = city_data.iloc[-1]

    coordinator = _get_coordinator()
    with st.spinner("Refreshing agent context…"):
        result = coordinator.run_all(
            city=city, city_data=city_data, latest=latest, models=models,
            feature_cols=feature_cols, build_feature_row=build_feature_row,
            attribution_df=attribution_df, enforcement_df=enforcement_df,
        )

    if any(a["status"] == "error" for a in result["agents"].values()):
        st.warning("One or more upstream agents failed for this city today — answers may be incomplete. "
                   "See the Multi-Agent AI Console for details.")

    history_key = f"chat_history_{city}"
    if history_key not in st.session_state:
        st.session_state[history_key] = []

    with st.container(key="assistant_chat_card"):
        st.markdown("<div style='height:2px;'></div>", unsafe_allow_html=True)

        st.markdown("<div class='xai-section-label' style='margin-top:0;'>Try asking</div>", unsafe_allow_html=True)
        sc = st.columns(3)
        for i, q in enumerate(SUGGESTED_QUESTIONS):
            if sc[i % 3].button(q, key=f"suggest_{city}_{i}", use_container_width=True):
                st.session_state[f"pending_question_{city}"] = q

        st.markdown("<div style='height:8px;'></div>", unsafe_allow_html=True)

        for turn in st.session_state[history_key]:
            with st.chat_message("user"):
                st.markdown(turn["question"])
            with st.chat_message("assistant", avatar="🤖"):
                st.markdown(turn["answer"])
                st.markdown(_citation_chips(turn["citations"]), unsafe_allow_html=True)

        pending = st.session_state.pop(f"pending_question_{city}", None)
        typed = st.chat_input(f"Ask about {city}'s air quality…")
        question = pending or typed

        if question:
            with st.chat_message("user"):
                st.markdown(question)

            qa = _get_query_agent()
            msg = qa.run(city, question, result)

            with st.chat_message("assistant", avatar="🤖"):
                if msg.status == "ok":
                    answer = msg.payload["answer"]
                    citations = msg.payload["citations"]
                    st.markdown(answer)
                    st.markdown(_citation_chips(citations), unsafe_allow_html=True)
                else:
                    answer = f"Sorry, I couldn't answer that: {msg.payload.get('error')}"
                    citations = []
                    st.error(answer)

            st.session_state[history_key].append({
                "question": question, "answer": answer, "citations": citations,
            })

        if st.session_state[history_key]:
            if st.button("🗑️  Clear conversation", key=f"clear_{city}"):
                st.session_state[history_key] = []
                st.rerun()
